In [2]:
import numpy as np


In [3]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
mat=np.matrix([1,2,3,4,5])
mat

matrix([[1, 2, 3, 4, 5]])

In [6]:
arr2=arr1
arr2

array([1, 2, 3, 4, 5])

In [7]:
arr2[0]=100

In [8]:
arr1

array([100,   2,   3,   4,   5])

In [9]:
arr2

array([100,   2,   3,   4,   5])

changes have been to arr1 as well because both arr1 and arr2 point at same memory location
to avoid this use np.copy().

In [10]:
arr3=np.copy(arr2)
arr3

array([100,   2,   3,   4,   5])

In [11]:
arr3[1]=200
arr3

array([100, 200,   3,   4,   5])

In [12]:
arr2

array([100,   2,   3,   4,   5])

In [13]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [14]:
np.fromfunction(lambda i,j:i*j,(3,3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [15]:
iterable=(i*i for i in range(5))

In [16]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [17]:
np.fromstring('234,236',sep=',')

array([234., 236.])

In [18]:
np.fromstring('234 236',sep=' ')


array([234., 236.])

In [19]:
arr1

array([100,   2,   3,   4,   5])

In [20]:
arr1.ndim#used to check dimension

1

In [21]:
arr4=np.array([[1,2,3,4],[5,6,7,8]])

In [22]:
arr4.ndim

2

In [23]:
arr4.size

8

In [24]:
arr1.shape

(5,)

In [25]:
arr4.shape#(row , column)

(2, 4)

In [26]:
list(np.arange(2.3,5.6))

[2.3, 3.3, 4.3, 5.3]

In [27]:
np.linspace(1,10,5)#will produce 5 data in between 1 to 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
on=np.ones((4,3))

In [35]:
on+5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [36]:
on*69

array([[69., 69., 69.],
       [69., 69., 69.],
       [69., 69., 69.],
       [69., 69., 69.]])

In [38]:
np.eye(3)#produces a identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.logspace(1,10,5,base=2)

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [43]:
np.random.randn(1,5)

array([[ 0.91987373, -0.99728474,  1.11305083, -0.74687978,  2.78846019]])

In [45]:
np.random.rand(3,3)

array([[0.3552399 , 0.88087922, 0.45203711],
       [0.73934868, 0.90696142, 0.3255339 ],
       [0.05373971, 0.09521579, 0.14119751]])

In [58]:
ar=np.random.randint(1,100,(3,4))

In [51]:
import random 
print(random.randrange(1,10))

6


In [52]:
data=np.random.randint(1,10,(300,300))

In [56]:
import pandas as pd
pd.DataFrame(data).to_csv('random.csv')

In [59]:
ar

array([[68, 47, 87, 31],
       [88, 47, 74, 40],
       [33, 58, 85, 46]])

In [66]:
ar=ar.reshape(6,2)
ar

array([[68, 47],
       [87, 31],
       [88, 47],
       [74, 40],
       [33, 58],
       [85, 46]])

In [65]:
ar[0][1]


47

In [73]:
ar[1:4,1]

array([31, 47, 40])

In [74]:
ar1=np.random.randint(1,100,(5,5))

In [75]:
ar1

array([[93, 18, 41, 20, 59],
       [15,  2, 76, 75, 75],
       [13, 43, 73, 59, 26],
       [24,  7, 40,  5, 24],
       [27, 84, 22, 54, 83]])

In [76]:
ar1>50

array([[ True, False, False, False,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True, False],
       [False, False, False, False, False],
       [False,  True, False,  True,  True]])

In [77]:
ar1[ar1>50]

array([93, 59, 76, 75, 75, 73, 59, 84, 54, 83])

In [81]:
ar1[2:4,(1,2)]

array([[43, 73],
       [ 7, 40]])

In [84]:
array1=np.random.randint(1,3,(3,3))
array2=np.random.randint(1,3,(3,3))


In [86]:
array1

array([[1, 1, 1],
       [2, 2, 1],
       [1, 1, 2]])

In [87]:
array2

array([[2, 2, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [85]:
array1+array2

array([[3, 3, 3],
       [3, 3, 2],
       [3, 2, 4]])

In [88]:
array1*array2

array([[2, 2, 2],
       [2, 2, 1],
       [2, 1, 4]])

In [89]:
array1@array2

array([[5, 4, 5],
       [8, 7, 8],
       [7, 5, 7]])

In [95]:
array1/0

C:\Users\vbhar\AppData\Local\Temp\ipykernel_10024\2251574936.py:1: RuntimeWarning: divide by zero encountered in divide
  array1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [96]:
np.sqrt(array1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356]])

In [97]:
np.exp(array1)

array([[2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [98]:
np.log10(array1)

array([[0.     , 0.     , 0.     ],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.30103]])

In [99]:
array3=np.random.randint(1,10,(3,4))

In [100]:
array3

array([[5, 4, 5, 6],
       [5, 7, 7, 4],
       [1, 4, 9, 9]])

In [101]:
array3.reshape(6,2)

array([[5, 4],
       [5, 6],
       [5, 7],
       [7, 4],
       [1, 4],
       [9, 9]])

In [103]:
array3.reshape(2,6)


array([[5, 4, 5, 6, 5, 7],
       [7, 4, 1, 4, 9, 9]])

In [104]:
array3.T

array([[5, 5, 1],
       [4, 7, 4],
       [5, 7, 9],
       [6, 4, 9]])

In [105]:
array3.flatten()

array([5, 4, 5, 6, 5, 7, 7, 4, 1, 4, 9, 9])

In [145]:
rizz=np.array([1,2,3,3,4])

In [146]:
rizz

array([1, 2, 3, 3, 4])

In [109]:
np.expand_dims(rizz,axis=0)#expands dimension by one

array([[1, 2, 3, 3, 4]])

In [110]:
np.repeat(rizz,2)

array([1, 1, 2, 2, 3, 3, 3, 3, 4, 4])

In [113]:
np.roll(rizz,shift=3)

array([3, 3, 4, 1, 2])

In [114]:
np.diag(rizz)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [115]:
array1

array([[1, 1, 1],
       [2, 2, 1],
       [1, 1, 2]])

In [116]:
array2

array([[2, 2, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [117]:
array3=np.array(['viraj','sharma'])

In [118]:
np.char.upper(array3)

array(['VIRAJ', 'SHARMA'], dtype='<U6')

In [119]:
np.char.title(array3)

array(['Viraj', 'Sharma'], dtype='<U6')

In [120]:
np.char.capitalize(array3)

array(['Viraj', 'Sharma'], dtype='<U6')

In [121]:
np.sin(array1)

array([[0.84147098, 0.84147098, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098],
       [0.84147098, 0.84147098, 0.90929743]])

In [122]:
np.cos(array1)

array([[ 0.54030231,  0.54030231,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231, -0.41614684]])

In [123]:
np.tan(array1)

array([[ 1.55740772,  1.55740772,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772],
       [ 1.55740772,  1.55740772, -2.18503986]])

In [124]:
np.tanh(array1)

array([[0.76159416, 0.76159416, 0.76159416],
       [0.96402758, 0.96402758, 0.76159416],
       [0.76159416, 0.76159416, 0.96402758]])

In [125]:
np.sqrt(array1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356]])

In [127]:
np.power(array1,2)

array([[1, 1, 1],
       [4, 4, 1],
       [1, 1, 4]], dtype=int32)

In [128]:
np.mean(array1)

1.3333333333333333

In [129]:
np.median(array1)

1.0

In [130]:
np.std(array1)

0.4714045207910317

In [131]:
np.var(arr1)

1490.9600000000003

In [132]:
np.max(array1)

2

In [147]:
rizz

array([1, 2, 3, 3, 4])

In [148]:
np.sort(rizz)

array([1, 2, 3, 3, 4])

In [149]:
np.searchsorted(rizz,2.5)

2